sudo: required
language: bash

# exclude tags
branches:
  except:
    - /^\d+$/

services:
  - docker

env:
  global:
    # build number used by blt pipeline
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    # disables gcloud installation prompts
    # - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # Install envtpl for easy templating.
  - sudo pip install envtpl

  # Login to mup.cr to publish artifacts
  # - docker login --username $DOCKER_LOGIN --password $DOCKER_PASS mup.cr

  # Install gcloud
  # - rm -rf ${HOME}/google-cloud-sdk
  # - curl https://sdk.cloud.google.com | bash;
  # - export PATH=${HOME}/google-cloud-sdk/bin:$PATH
  # - gcloud components install kubectl

  # authenticate gcp requests the gcloud cli tool makes
  # - echo $GCP_SECRET > client-secret.json
  # - gcloud auth activate-service-account --key-file client-secret.json
  # - export GOOGLE_APPLICATION_CREDENTIALS="$TRAVIS_BUILD_DIR/client-secret.json"

script:
  # - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then make publish && make deploy-prod; else make package; fi
  # Remove the following line when un-commenting the line above
  - make package

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$(make version)
  - echo "GIT_TAG=$GIT_TAG"
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git tag $GIT_TAG -f -a -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID"
    || true
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] &&
    git push --tags || true

